### ISSUE TITLE
Should align versions of RxJava being used

### ISSUE THREAD

**Issue by cvgaviao** [jklingsporn/vertx-jooq#103]
Those dependencies below are pointing to different versions of rxjava.
The `vertx-rx-java2` has `rxjava`as a dependency and it is pointing to 2.2.4 while `rx.version` property is pointing to 2.1.3.

But that setup makes maven to use the version 2.1.3 

```
        <dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>${rx.version}</version>
        </dependency>
        <dependency>
            <groupId>io.vertx</groupId>
            <artifactId>vertx-rx-java2</artifactId>
            <version>${vertx.version}</version>
        </dependency>
```

**Comment by cvgaviao** [comment]
I think the best would be to remove the dependency to rxjava and let the vertx-rx-java2 drive which version to use.

**Comment by cvgaviao** [comment]
Hi @jklingsporn. 
May I ask you how do you drive your branchs? I would like to try your fix and close this issue but I got lost. Your development branch is older than the master. and master is set to version 4.1.0 instead to 4.2.0-SNAPSHOT...

**Comment by jklingsporn** [comment]
The new branch is here: https://github.com/jklingsporn/vertx-jooq/tree/release4.2.0
