### ISSUE TITLE
How to use Generated Records?

### ISSUE THREAD

**Issue by don-yan** [jklingsporn/vertx-jooq#106]
Hi, 

I'm going through the JOOQ tutorial and am having difficulty understanding if I can use Records with your plugin.

```java
Configuration jooqConfig = new DefaultConfiguration().set(SQLDialect.MYSQL);
AsyncClassicGenericQueryExecutor queryExecutor = new AsyncClassicGenericQueryExecutor(jooqConfig, mySQLClientAsync);

Future<Integer> updatedCustom = queryExecutor.execute(dslContext -> {

    //  ## Fails Immediately ## //   
    FormRecord formRecord = dslContext.fetchOne(Tables.FORM, Tables.FORM.ID.eq(1));
    formRecord.setIsActive(false);
    formRecord.store();
     
    // ## This Works ## //            
     return   dslContext.update(Tables.FORM)
                                     .set(Tables.FORM.DESCRIPTION, "this works")
                                     .where(Tables.FORM.ID.eq(1));
});
```

`fetchOne` fails immediately
> org.jooq.exception.DetachedException: Cannot execute query. No Connection configured

Thanks for any help

**Comment by don-yan** [comment]
I was able to get it working by passing another connection to the JOOQ config.

I understand that this negates the purpose of async, but I'm still confused why the generator generates the Record objects.

Being able to chain statements without all of the nested callbacks seems useful.

Is this a use-case for the RX apis?

Sorry if this is obvious, I'm still wrapping my head around Vert.x & JOOQ

**Comment by jklingsporn** [comment]
Hi @don-yan, 
active records do not work directly with vertx-jooq. As you may have noticed, there are three different driver implementations of vertx-jooq:
- vertx-jooq-async
- vertx-jooq-reactive
- vertx-jooq-jdbc
The first two implementations only use the `org.jooq.Configuration` to determine which dialect should be rendered by jOOQ. The actual query execution is handled by the vertx `AsyncSQLClient` (`PGClient` for reactive modules respectively). That means you cannot use any `store`, `update` or `fetch` methods provided by jOOQ at all and you should either use the DAO- or `QueryExecutor`-methods for this.
The closest you can get is using vertx-jooq-jdbc which should complete your example code without errors as it uses jOOQ not only to generate SQL but also for execution.

**Comment by rdinkel** [comment]
Hi @jklingsporn 
Is there any way that vertx-jooq-reactive will have the store, fetch and update methods in near future ?
