### ISSUE TITLE
How to execute raw sql using RXQueryExecutor

### ISSUE THREAD

**Issue by paninics** [jklingsporn/vertx-jooq#112]
This is not a bug but a question on how to execute raw SQL statements.

In jOOQ, one can do the following:
```
String selectQuery = ...;
Result<Record> res = dsl.fetch(selectQuery);
```

How can we do the equivalent when using `RXQueryExecutor`? I do not have the flexibility to build a `Query` object rather I'm given a select query statement (pulled from an external source) as a `String` and have to execute it using Rx and process the result.

**Comment by jklingsporn** [comment]
- If you are using the JDBC-variant, you can use the `executeAny`-method to execute arbitrary SQL.
- If the result is of any type (e.g. not the record-type from the `QueryExecutor`) than I'm afraid you have to use the underlying delegate, e.g. the ReactivePGClient or the AsyncClient for query execution
- If the result is the same record-type as defined in the `QueryExecutor` you have to somehow convert the `String` to a `ResultQuery` of that type. `DSL.resultQuery("yourPredefinedStringQuery")` comes closest, but you need to properly cast it somehow to your record-type.

**Comment by paninics** [comment]
Thank you. After browsing through the source code, here's what I'd come up as an interim until you responded with your suggestions. Do you see any pitfalls, apart from relying on some internal logic / api of vertx-jooq?

For the JDBC variant:

```
public Single<QueryResult> query(String sql) {
	return RXTool.executeBlocking(h -> h.complete(new JDBCQueryResult(dsl.fetch(sql))), vertx);
}
```

For the ReactivePGClient 

```
public Single<QueryResult> query(String sql) {
	return pgClient.rxPreparedQuery(sql).map(res -> new ReactiveQueryResult(res.getDelegate()));
}
```

I've tried to keep the API similar to what's already present in the Rx QueryExecutors i.e.

```
public <R extends Record> Single<QueryResult> query(Function<DSLContext, ? extends ResultQuery<R>> queryFunction)
```

**Comment by jklingsporn** [comment]
Looks good imho.
