### ISSUE TITLE
Add support for vert.x 3.8.0

### ISSUE THREAD

**Issue by EnilPajic** [jklingsporn/vertx-jooq#115]
Hello,

vert.x 3.8.0 is here, and it is not compatible with current vertx-jooq, because vert.x introduced Promises as a replacement for Futures, among other changes. Do you have any plans on upgrading vertx-jooq to support vert.x 3.8.0 and later? 

Thank you in advance!

**Comment by aleksandar78** [comment]
Hi,

I'm using vertx-jooq 4.1.0 with vertx 3.8.1. 
I've started using this library two weeks ago and for now, I didn't find any limitation or compatibility issue. 
As a not expert maybe I missed something?

**Comment by EnilPajic** [comment]
It may depend on what are you using? vertx-jooq has 16 submodules with different purposes.
You can see [this pull request](https://github.com/jklingsporn/vertx-jooq/pull/114) from @inve1 which, among other, changed futures (pre 3.8.0) to promises. As I see now, vertx-jooq author responded to pull request, and it seems that it is all fixed in 5.0.0 (https://github.com/jklingsporn/vertx-jooq/tree/release5.0.0).
In the meantime, I used PR from @inve1 and it worked.
