### ISSUE TITLE
insert query with jsonb wrongly generated

### ISSUE THREAD

**Issue by Globegitter** [jklingsporn/vertx-jooq#118]
If I have (kotlin) code like:

```
        val insert = eventDao.queryExecutor().execute {
            it.insertInto(Tables.EVENT)
                .set(Tables.EVENT.META, JsonObject(mapOf("meta" to "bar")))
        }
```

I get a prepared query of `insert into "public"."event" ("meta") values ($2::json)` and then a failure of `io.vertx.pgclient.PgException: could not determine data type of parameter $1`.

The issue being that somehow the quer gets generated with a `$2` rather than a `$1` and I have not been able to figure out why. If I use a column in my table of any other type it works fine. But all my jsonb columns have this issue. The issue is the same if I try to insert multiple columns.

I have not tried it with a json column. Any idea what the issue could be? Let me know if there is any more information you need or a reproduction case.

**Comment by Globegitter** [comment]
Ok, it seems to be an issue specificall with jooq 3.12 and having `forcedTypes` setting `JSONB` to `io.vertx.core.json.JsonObject` as described in various places in this repository. When I leave the `forcedTypes` config out and use the new `JSONB` object that is required by jooq 3.12 I get an error in the vertx postgresql client itself: `Exception in thread "main" io.vertx.core.impl.NoStackTraceThrowable: Values [{}, {}] cannot be coerced to [Object, Object]` presumably because it does not know what to do with the `JSONB` object.

**Comment by Globegitter** [comment]
Ok, I managed to hack something together for jooq 3.12:

I had to add
```
if (JsonObject.class.isAssignableFrom(param.getBinding().converter().toType())) {
            return param.getValue()
        }
```

to the `convertToDatabaseType` method in `AbstractReactiveQueryExecutor.java` as well as create my own JSONB to JsonObjectBinding. Here is the code in kotlin:

```
import io.vertx.core.json.JsonObject
import java.sql.SQLException
import java.sql.SQLFeatureNotSupportedException
import java.sql.Types
import java.util.Objects
import mu.KotlinLogging
import org.jooq.*

class JsonbToJsonObjectBinding : Binding<JSONB, JsonObject> {

    // The converter does all the work
    override fun converter(): Converter<JSONB, JsonObject> {
        return CONVERTER
    }

    override fun sql(ctx: BindingSQLContext<JsonObject>) {
        ctx.render().sql("${ctx.convert(converter()).variable()}::json")
    }

    @Throws(SQLException::class)
    override fun register(ctx: BindingRegisterContext<JsonObject>) {
        ctx.statement().registerOutParameter(ctx.index(), Types.VARCHAR)
    }

    @Throws(SQLException::class)
    override fun set(ctx: BindingSetStatementContext<JsonObject>) {
        ctx.statement().setString(ctx.index(), Objects.toString(ctx.convert(converter()).value(), null))
    }

    @Throws(SQLException::class)
    override fun get(ctx: BindingGetResultSetContext<JsonObject>) {
        ctx.convert(converter()).value(JSONB.valueOf(ctx.resultSet().getString(ctx.index())))
    }

    @Throws(SQLException::class)
    override fun get(ctx: BindingGetStatementContext<JsonObject>) {
        ctx.convert(converter()).value(JSONB.valueOf(ctx.statement().getString(ctx.index())))
    }

    @Throws(SQLException::class)
    override fun set(ctx: BindingSetSQLOutputContext<JsonObject>) {
        throw SQLFeatureNotSupportedException()
    }

    @Throws(SQLException::class)
    override fun get(ctx: BindingGetSQLInputContext<JsonObject>) {
        throw SQLFeatureNotSupportedException()
    }

    companion object {

        private val CONVERTER = object : Converter<JSONB, JsonObject> {
            override fun from(t: JSONB?): JsonObject? {
                return JsonObject(t?.toString())
            }

            override fun to(u: JsonObject?): JSONB? {
                return JSONB.valueOf(u.toString())
            }

            override fun fromType(): Class<JSONB> {
                return JSONB::class.java
            }

            override fun toType(): Class<JsonObject> {
                return JsonObject::class.java
            }
        }
    }
}
```

Will test the 5.0 release branch and see how that is working.

**Comment by gtejasvi** [comment]
[Related Issue 107](https://github.com/jklingsporn/vertx-jooq/issues/107)
