### ISSUE TITLE
When using enum values that are not Java names, `fromJson()` rejects such values

### ISSUE THREAD

**Issue by guss77** [jklingsporn/vertx-jooq#12]
The problem is that `fromJson` uses `Enum.valueOf()` to get the correct enum value generated by the Jooq Java generator, which in turn "normalizes" the values from the database to Java names (otherwise the enum won't compile, obviously).

So in my case, my field looks like this:

```
  `direction` ENUM('inbound', 'outbound', 'public-inbound') NOT NULL,
```

which Jooq generates to:

```
public enum TableDirection implements EnumType {
    inbound("inbound"),
    outbound("outbound"),
    public_inbound("public-inbound");
```

Now when I pass the JSON value `{"direction": "public-inbound"}` I get an exception, while `{"direction": "public_inbound"}` works fine.

The way I see it, `fromJson()` should lookup the actual text value of the enum instead of the normalized Java name.

**Comment by jklingsporn** [comment]
Thanks for the report. 
Until I have a fix for this you can subclass the VertxGenerator and overwrite `protected boolean handleCustomTypeFromJson(TypedElementDefinition<?> column, String setter, String columnType, String javaMemberName, JavaWriter out)` and `protected boolean handleCustomTypeToJson(TypedElementDefinition<?> column, String getter, String columnType, String javaMemberName, JavaWriter out)` to handle that enum by yourself.
