### ISSUE TITLE
execute blocking should be used with ordered parameterized version 

### ISSUE THREAD

**Issue by subhashkadam** [jklingsporn/vertx-jooq#122]
https://github.com/jklingsporn/vertx-jooq/blob/0db00b5e040639c309691dfbc125034fa3346d88/vertx-jooq-classic-jdbc/src/main/java/io/github/jklingsporn/vertx/jooq/classic/jdbc/JDBCClassicGenericQueryExecutor.java#L35

execute blocking should be used with ordered parameter. it causes all executions in sequence.

ref -  https://vertx.io/docs/kdoc/vertx/io.vertx.reactivex.core/-vertx/execute-blocking.html

**Comment by jklingsporn** [comment]
Hello and thank you for your report. 
I am not sure if I understand correctly: by default the `ordered`-parameter is set to `true` and that is actually the desired behavior. Imagine an INSERT, followed by an UPDATE statement. If `ordered` would be set to `false` it might happen that the UPDATE is executed _before_ the INSERT statement.
Or am I missing something?

**Comment by subhashkadam** [comment]
Hey,
The case which you are saying should be executed in transaction as per my
understanding; when u need such behaviour. Else this will cause you
performance issues as all the request to database will get queued. And we
will not get required performance benifit of vertx. All the request from
different api calls are waiting in queue .. and when you have lots of
requests.. their response time may increase on number of requests increases.
Hope this clears things up for you.

Thanks

**Comment by jklingsporn** [comment]
This totally makes sense. I will incorporate your changes as soon as I find the time.

**Comment by subhashkadam** [comment]
Thanks a lot..

**Comment by jklingsporn** [comment]
Will be implemented in 4.2.1
