### ISSUE TITLE
Generated findManyByXYZ-methods should take Collection<T> instead of List<T> as an argument

### ISSUE THREAD

**Issue by jklingsporn** [jklingsporn/vertx-jooq#126]
There is no reason to not have other collections as argument.

**Comment by aleksandar78** [comment]
Absolutely, Set<T> is a preferred collection over List<T> for many Java developers.
Generalization is nearly always a good thing.

**Comment by jklingsporn** [comment]
>Set is a preferred collection over List for many Java developers.
I wouldn't go that far, but in this case Sets make more sense, yes.

Aleksandar <notifications@github.com> schrieb am Fr., 31. Jan. 2020, 21:31:
