### ISSUE TITLE
Error querying instance of ReactiveClassicGenericQueryExecutor

### ISSUE THREAD

**Issue by nixos89** [jklingsporn/vertx-jooq#132]
@jklingsporn I have an issue with performing _execute(..)_ method on _ReactiveClassicGenericQueryExecutor_ **instance** by following tutorial from this [page](https://github.com/jklingsporn/vertx-jooq/tree/master/vertx-jooq-classic-reactive) where it reports an error saying that  _execute(Function<DSLContext, ? extends Query> queryFunction)_ method arguments of class _ReactiveClassicGenericQueryExecutor_ are not applicable for arguments of _UpdateConditionStep<CategoryRecord>_  (which of course is return type of `where` method).

Here is a screenshot of error showed in Eclipse IDE 2019-06:
![querying_error](https://user-images.githubusercontent.com/12121415/75154147-604be780-570d-11ea-862d-ec65aa098e4f.png)

Also, I am using Long type for CATEGORY_ID field and here is [link](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/master/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/MainVerticle.java) of my repo (I commented out lines 100-113 due to error reporting in MainVerticle, and other methods which are implemented are there for CRUD methods and for creating tables if needed by using predefined queries in [DBQueries class](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/master/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/DBQueries.java))

Am I missing something (method invocation after `where` method) or is this unresolved bug?
Thank you in advance. :)

**Comment by jklingsporn** [comment]
You are supposed to use the `execute`-Function like so:
```
queryExecutor.execute(dslContext -> dslContext.update(Tables.FOO).set(Tables.FOO.BAR,"bar").where(Tables.FOO.ID.eq(123))
```
No need to create a `DSLContext` by your self.

**Comment by jklingsporn** [comment]
That being said, the tutorial is wrong. I will fix that.

**Comment by nixos89** [comment]
It works!  :+1: 
Thank you for quick reply and time. :)
