### ISSUE TITLE
Compile error on generated field from a json column

### ISSUE THREAD

**Issue by cvgaviao** [jklingsporn/vertx-jooq#135]
I'm trying to setup the generation (ClassicReactiveVertxGenerator) of a table that contains a json column.
Without any setup the pojo's method generated is:
```
    /**
     * The column <code>admin.State.phone_code</code>.
     */
    public final TableField<StateRecord, JSON> PHONE_CODE = createField(DSL.name("phone_code"), org.jooq.impl.SQLDataType.JSON, this, "");
```

But since I'm using the `vertx-pg-client` driver, whose queries returns a `ROW` with a `io.vertx.core.json.JsonArray` column object, I've tried with the following forcedType:
```
<forcedType>
    <userType>io.vertx.core.json.JsonArray</userType>
    <converter>io.github.jklingsporn.vertx.jooq.shared.JsonArrayConverter</converter>
    <includeExpression>phone_code</includeExpression>
    <includeTypes>.*\.json</includeTypes>
</forcedType>
```
It is generating this method:
```
    /**
     * The column <code>admin.State.phone_code</code>.
     */
    public final TableField<StateRecord, JsonArray> PHONE_CODE = createField(DSL.name("phone_code"), org.jooq.impl.SQLDataType.JSON, this, "", new JsonArrayConverter());
```
But with the following compile error:
```
The method createField(Name, DataType<T>, Table<R>, String, Converter<T,U>) in the type AbstractTable<StateRecord> is not applicable for the arguments (Name, DataType<JSON>, State, String, JsonArrayConverter)
```

**Comment by cvgaviao** [comment]
I also tried to use the following binding with no luck:
```
<forcedType>
	<userType>io.vertx.core.json.JsonArray</userType>
	<binding>io.github.jklingsporn.vertx.jooq.shared.ObjectToJsonArrayBinding</binding>
	<includeTypes>.*\.json</includeTypes>
	<includeExpression>phone_code</includeExpression>
</forcedType>
```

**Comment by jklingsporn** [comment]
Please try one of the following converters: https://github.com/jklingsporn/vertx-jooq/tree/master/vertx-jooq-shared/src/main/java/io/github/jklingsporn/vertx/jooq/shared/postgres

**Comment by cvgaviao** [comment]
Interesting...
The one that worked was the least expected, because it converts from `org.jooq.JSON` to `io.vertx.core.json.JsonArray`.
```
<forcedType>
    <userType>io.vertx.core.json.JsonArray</userType>
  <converter>io.github.jklingsporn.vertx.jooq.shared.postgres.JSONToJsonArrayConverter</converter>
    <includeExpression>phone_code</includeExpression>
    <includeTypes>.*\.json</includeTypes>
</forcedType>
```
Could you explain it, please ? :)

**Comment by jklingsporn** [comment]
Sure: the `JsonArrayConverter`, converts a `String`-field into a `JsonArray`. Before jOOQ 3.12.3 there was no dedicated data type for JSON-columns so one could treat it as a `String`. After the release the new data types `JSON` and `JSONB` were added. To avoid any breaking changes, the new converters, like `JSONToJsonArrayConverter` were added.

**Comment by cvgaviao** [comment]
Ok, thanks !
