### ISSUE TITLE
Vertx 4.0.0 support

### ISSUE THREAD

**Issue by cvgaviao** [jklingsporn/vertx-jooq#136]
The class `io.vertx.sqlclient.impl.ArrayTuple` was changed in version 4.0.0 and it doesn't have the method add() anymore.
`io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveQueryExecutor.getBindValues()` must be changed in order to use `addValue(value)` instead. this method already exists in 3.8.5.

---
```
    protected Tuple getBindValues(Query query) {
        ArrayTuple bindValues = new ArrayTuple(query.getParams().size());
        for (Param<?> param : query.getParams().values()) {
            if (!param.isInline()) {
                Object value = convertToDatabaseType(param);
                bindValues.addValue(value);
            }
        }
        return bindValues;
    }
```

**Comment by jklingsporn** [comment]
Yes, vertx 4.0 is not supported yet, as it is in alpha/beta state.

**Comment by cvgaviao** [comment]
Well, this minor change won't impact older versions since 3.8.5 already has the method left on 4.0.0.

Btw, they already published some milestones... and I'm using it into my new project already. There are awesome improvements on it.

**Comment by jklingsporn** [comment]
Ah didn't read that properly. Thx for your contribution.

**Comment by UkonnRa** [comment]
Vertx 3.9.0 is realeased. And `ArrayTuple#add` has already been removed, please update to `addValue` instead

**Comment by UkonnRa** [comment]
The thing is, in `3.9.0`, the definition is:
```
public class ArrayTuple implements TupleInternal {
  ...
}
```

But in `3.8.0` or `4.0.0-milestone4`, the definition is:
```
public class ArrayTuple extends ArrayList<Object> implements TupleInternal {
  ...
}
```

I am afraid that this is a breaking change
