### ISSUE TITLE
Add @DataObject for generated POJOs

### ISSUE THREAD

**Issue by zou8944** [jklingsporn/vertx-jooq#140]
It is perfect to generate POJO with `fomJson` and `toJson`, but is it possible to add @DataObject to generated POJOs also? if so , we can use it in service proxies. refer to [Service proxies doc](https://vertx.io/docs/vertx-service-proxy/java/#_restrictions_for_service_interface), the asynchronous result can only be primitive/json/enum, and class annotated with @DataObject

**Comment by jklingsporn** [comment]
This totally makes sense. Will see how fast I can add it.

**Comment by zou8944** [comment]
On the other hand, I noticed that the generated DAO classes have methods like `findManyByxxx`/`findOneByxxx` which accept `Condition` parameter. But I don't know how to add order by segment and execute complex queries like join, could you please advide ?

**Comment by jklingsporn** [comment]
I'd just add `@DateObject`-support for the POJOs for now. 
Using DAOs via service proxies would be the next thing and out of the scope of this issue. What you can do for converting the `Condition` is to convert it into a `String` on one side and convert it back afterwards using `DSL.condition(String)` method.

**Comment by zou8944** [comment]
you mean this ?
```kotlin
contentDao.findManyByCondition(DSL.condition(CONTENT.ID.gt(begin).toString() + "order by id desc limit 10"))
```

**Comment by jklingsporn** [comment]
What I mean is, if you need to remotely call a function that takes a `Condition` as an argument you have to convert it into a string before. So let's assume there is a wrapper around the dao that replaces the methods that take a `Condition`, like `findOneByCondition(Condition)` with `findOneByCondition(String)`. The wrapper would do something like this
```
public Future<P> findOneByCondition(String condition){
  return dao.findOneByCondition(DSL.condition(condition));
}
```

**Comment by jklingsporn** [comment]
It was more work to add this annotation as expected. As described in https://github.com/jOOQ/jOOQ/issues/10355 I had to cook a lot copy pasta to achieve this functionality. I will remove the duplicate code once it is implemented.
