### ISSUE TITLE
JSONB to JsonObject Convertor Failure when using postgres reactive classic

### ISSUE THREAD

**Issue by gtejasvi** [jklingsporn/vertx-jooq#148]
While accessing JSONB data from postgres using the convertor JSONBToJsonObjectConverter  record inserts are failing with an error message:
`java.lang.AssertionError: io.vertx.core.impl.NoStackTraceThrowable: Parameter at position[2] with class = [org.jooq.JSONB] and value = [{"val":"mytestval"}] can not be coerced to the expected class = [java.lang.Object] for encoding.`

If I use the JSONBToJsonObjectBinding Instead of the Converter the issue [107](https://github.com/jklingsporn/vertx-jooq/issues/107) seems to be reproduced where i notice that when the convertor is called the parameter index seems to be skipping the parameter value in the below logs (Parameter :4 seen instead of :3):
````
[insert into "public"."envconfig" ("id", "env", "key", "value", "created_by", "created_on", "updated_by", "updated_on", "dbts") 
values (default, :1, :2, cast(:4 as jsonb)::jsonb]
parameters   [NAMED]
bind index   [4]
cast mode    [DEFAULT]
declaring    [-]
subquery     [0] 
````
The failure message in this case is different `io.vertx.pgclient.PgException: could not determine data type of parameter $3`

**Comment by jklingsporn** [comment]
Thank you for your report. I'm looking into it.

**Comment by jklingsporn** [comment]
Fixed here: https://github.com/jklingsporn/vertx-jooq/tree/release5.1.2

**Comment by gtejasvi** [comment]
Tested this fix from the snapshot source and able to insert and retrieve JSONB columns.

**Comment by paomian** [comment]
got same issue at 6.5.5
