### ISSUE TITLE
Getting ERROR Connection not open CLOSED when composing Futures using vertx-jooq-classic-reactive: 5.0.1

### ISSUE THREAD

**Issue by nixos89** [jklingsporn/vertx-jooq#150]
Hi,
I have an issue when multiple Futures are being composed in order to perform **update** _Book_ table and **insert/delete** certain rows in intermediate tables _Category_Book_ and _Author_Book_ since _Book_ is connected with Many-To-Many relationship with Author and Category. Error message that I get in console is:

> ERROR com.ns.vertx.pg.BookJooqQueries - Error, something failed in deleteCategoryBookFuture.compose(..)! Cause: io.vertx.core.VertxException: Connection not open CLOSED

Also, I am using mixture of DAO instances and _execute()_ method on instance of _ReactiveClassicGenericQueryExecutor_ class. This is [repo link](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/book_CRUD/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/BookJooqQueries.java) to my class where I am getting this error and this is [HttpVerticle](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/book_CRUD/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/HttpVerticle.java) where routes, DAOs and other configuration is taking place for my RESTful web services.

I don't know if there is a possibility that I've "over-composed" Future instances and that's what's causing this error, but as I understood composition is used when certain operations (_Insert/Delete/Update_) need to be performed in sequential order and all have to succeeded.

Libraries I am using:
**Vert.x version:** 3.8.2
**vertx-jooq-classic-reactive**: 5.0.1
**postgre-sql**: 42.2.2 (Postgre DB is version 11.7 on my machine)

NOTE: I have these changes made in my **book_CRUD** branch, not to be mistaken with **master** (as I don't want to merge these not fully functional changes).
Thank you in advance

**Comment by jklingsporn** [comment]
Hey, thanks for your report. However the links you provided are not working.

**Comment by nixos89** [comment]
Hi @jklingsporn ,
sorry for that  - I had repo on public than switched it to private. Should be working now. :)
More details (if needed) for running app are in [README](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/book_CRUD/README.md) file.

**Comment by jklingsporn** [comment]
So I am not 100% what you are trying to do there, but [this line](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/book_CRUD/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/BookJooqQueries.java#L221) confuses me a bit. 
Is it wanted behavior that you execute the delete before the insert?
```
Future<Integer> insertBCFuture = categoryBookDAO.insert(bookCategories);
deleteCategoryBookFuture.compose(res -> insertBCFuture).setHandler(finalRes -> {
...
```
Or do you want to rather have it this way:
```
deleteCategoryBookFuture.compose(res -> categoryBookDAO.insert(bookCategories)).setHandler(finalRes -> {
...
```
All in all it's weird that you do the async-stuff in the `setHandler`-method, but I guess you did it for debugging? Regarding this question:

>I don't know if there is a possibility that I've "over-composed" Future instances and that's what's causing this error, but as I understood composition is used when certain operations (Insert/Delete/Update) need to be performed in sequential order and all have to succeeded.

There is no such thing as "over-composing". However it is important that you actually use `Future.compose` to apply a first-this-then-that-mechanic. Mixing DAOs and QueryExecutor-calls should be fine.

**Comment by nixos89** [comment]
Hi @jklingsporn,
exactly (I want to **execute the delete before the insert**)! What I am trying to do is to delete Category IDs (which are not in JSON Request Body) filtered at [this line ](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/book_CRUD/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/BookJooqQueries.java#L194) so I don't have to DELETE and INSERT **SAME** Category IDs (that were ALREADY THERE) in intermediary CategoryBook table (hope it makes sense :-) ). 

I know this isn't the best practice (styled async code), but I don't have much experience in writing async-code and YES, I did it for easier DEBUGGING. As matter of "over-composing" I thought that something could've happened due to long time response for Futures to be executed and therefore mentioned Error has occurred.

**P.S.** I've even tried to swap order of Futures: 
  `insertBCFuture.compose(res -> deleteCategoryBookFuture).setHandler(finalRes -> {`
...but I keep getting the same error.
Any advice?

**Comment by jklingsporn** [comment]
But what you are doing right now is executing the insert and the delete
simultaneously.

Nikola Stevanović <notifications@github.com> schrieb am Mi., 29. Apr. 2020,
11:37:

**Comment by nixos89** [comment]
I did try to that what you have suggested (sorry didn't mention that) that is:
deleteCategoryBookFuture.compose(res -> `categoryBookDAO.insert(bookCategories)).setHandler(finalRes -> {`
...but it still gives me same error and response keeps on hanging in Postman.
Here's an screenshot:
![Error due to Connection not open CLOSED](https://user-images.githubusercontent.com/12121415/80610495-ba349a80-8a39-11ea-8b02-8f72507dfbb6.png)
...and pushed a new branch (**03-fix_book_update**) with [edited line](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/e3e42faf4f87d94d93856f539e95461afb20e322/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/BookJooqQueries.java#L220) as you suggested.

**Comment by jklingsporn** [comment]
Can you try out my "fix". I cleaned up the code a bit.
https://github.com/jklingsporn/VertxPgReactiveJOOQ/tree/03-fix_book_update
Also, I'd suggest to move to Vertx 3.9 as that release added some syntactic sugar to the Future with methods like `onComplete`, `onSuccess`, `onFailure`, `recover`, etc.

**Comment by nixos89** [comment]
Hi @jklingsporn ,
I've managed to fix it as you suggested (it worked like a charm, thank you so much :-) ) and [here](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/2f7a55621ca7366a7129d5b4b408f1c1d3593b87/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/BookJooqQueries.java#L180) is the code for changed methods which iterate through intermediary tables here which is using **vertx 3.8.2 version** and **vertx-jooq-classic-reactive 5.0.1** version.
**NOTE:** I had to make checks for empty/non-empty collections of updated Author/Category IDs  because vertx reports an ERROR when I try to insert/delete EMPTY collection!

I also switched to vertx 3.9.0 and had breaking changes (like in screenshot below) 
![breaking-changes-switching-from-3 8 2-to-3 9-vertx-version](https://user-images.githubusercontent.com/12121415/80797008-f6363f80-8ba0-11ea-980b-0f2dd6411b31.png)
...so I ALSO had to update **vertx-jooq-classic-reactive** to 5.1.1 version in order to be able to function properly. I've created new branch and here is the [pom.xml](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/04-switch-to-vertx-3.9.0/vertx-pg-reactive-jooq/pom.xml) and so far everything works.

If you look at the posted screenshot in HttpVerticle at line 202 in .onComplete() method there MUST be additional parentheses which are surrounding [this](https://github.com/nixos89/VertxPgReactiveJOOQ/blob/2f7a55621ca7366a7129d5b4b408f1c1d3593b87/vertx-pg-reactive-jooq/src/main/java/com/ns/vertx/pg/ActionHelper.java#L35) method. Do you have any idea why is that?

**Comment by jklingsporn** [comment]
No. I guess this is a mistake by the ide

Nikola Stevanović <notifications@github.com> schrieb am Fr., 1. Mai 2020,
12:08:

**Comment by jklingsporn** [comment]
Not sure how these transactions work, but if you need transactional db integrity, you will have to use the transactions provided by the QueryExecutor.

**Comment by nixos89** [comment]
> Not sure how these transactions work, but if you need transactional db integrity, you will have to use the transactions provided by the QueryExecutor.

Does that mean you are referring to [this](https://github.com/jklingsporn/vertx-jooq/blob/master/vertx-jooq-classic-reactive/src/main/java/io/github/jklingsporn/vertx/jooq/classic/reactivepg/ReactiveClassicQueryExecutor.java#L45) implementation and therefore I should switch to using its methods and leave out (Book/Author/Category)DAO instance methods to achieve DB intergrity?

**Comment by jklingsporn** [comment]
Yes, dao methods run outside of transactions. Now that I'm thinking about it this could be changed to allow transactions of one specific dao, but I guess you need to span the transaction across dao boundaries and that is currently not possible.

**Comment by nixos89** [comment]
> Yes, dao methods run outside of transactions.

that means: for NOW, I need to **refactor** my methods in BookJooqQueries class so they **do NOT use Book/Author/Category)DAO instance methods**, but methods of **ReactiveClassicQueryExecutor class** ?
If that's the case I have a problem when I am dealing with Many-To-Many connections as  insertReturningPrimary() method does NOT exist in it's stated by [@aleksandar78 ](https://github.com/jklingsporn/vertx-jooq/issues/120#issuecomment-580911601) so do I need to do something like this in [Simplified transaction API](https://vertx.io/docs/vertx-pg-client/java/#_simplified_transaction_api), NOT [Transactions with connections](https://vertx.io/docs/vertx-pg-client/java/#_transactions_with_connections) as much I can see in [this method](https://github.com/jklingsporn/vertx-jooq/blob/f742231872ecd300962e4c730ef62c596beef975/vertx-jooq-classic-reactive/src/main/java/io/github/jklingsporn/vertx/jooq/classic/reactivepg/ReactiveClassicGenericQueryExecutor.java#L72) _io.vertx.sqlclient.Transaction interface_ is being used...or is there more convenient way to handle transactions?

**Comment by jklingsporn** [comment]
Usually transactions are implemented using ThreadLocals but that is not
working with async programming because each sql statement might be
processed by a different thread. Also, imagine simultaneous calls on one
dao by http requests, so a per-dao transaction is not applicable too.
That being said, the only way is to go with the transaction-methods on the
QueryExecutor.

Nikola Stevanović <notifications@github.com> schrieb am Sa., 2. Mai 2020,
09:47:

**Comment by nixos89** [comment]
Thank you one again @jklingsporn for this info. :-) I've researched ThredLocal class, transaction methods in **ReactiveClassicGenericQueryExecutor** class and implemented transaction() method from same (QueryExecutor class). Now I'm having problem with saving Book table due to vertx-jooq API restrictions, so in order not to continue discussion in closed issue (where DAO classes are being used) I have created a [new issue](https://github.com/jklingsporn/vertx-jooq/issues/154). Please take a look when you get a chance. Thank you in advance.

Best regards,
Nikola
