### ISSUE TITLE
Error generating RowMappers in Windows

### ISSUE THREAD

**Issue by jmunozlor** [jklingsporn/vertx-jooq#161]
Hi,

We have a problem with generation of records with vertx-jooq plugin in Windows.
Maven configuration included:

		<generator>
                        <name>io.github.jklingsporn.vertx.jooq.generate.rx.RXReactiveVertxGenerator</name>
                        <database>
                            <name>org.jooq.meta.postgres.PostgresDatabase</name>
                            <includeRoutines>false</includeRoutines>
                            <schemata>
                                <schema>
                                    <inputSchema>users</inputSchema>
                                </schema>
                            </schemata>

                        </database>
                        <generate>
                            <interfaces>true</interfaces>
                            <daos>true</daos>
                            <fluentSetters>true</fluentSetters>
                        </generate>
                        
                        <strategy>
                            <name>io.github.jklingsporn.vertx.jooq.generate.VertxGeneratorStrategy</name>
                        </strategy>
                        <target>
                            <packageName>com.ab.domain</packageName>
                            <directory>src/main/java</directory>
                        </target>
                    </generator>

This is the error trace:

[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.13.3:generate (default) on project ab: Error running jOOQ code generation tool: Error generating code for catalog: Error generating code for schema users: character to be escaped is missing

The last shown trace is "Generate RowMappers ...". We believe that error is generated in next one link:

https://github.com/jklingsporn/vertx-jooq/blob/6364c2304aeb0b365e054aacb21e7bb895df4905/vertx-jooq-generate/src/main/java/io/github/jklingsporn/vertx/jooq/generate/builder/ComponentBasedVertxGenerator.java#L237

We suggest changing File.separator to Matcher.quoteReplacement(File.separator)

In the same way, we have tried in MAC OS and this problem doesn't happen, only in Windows.

Thank you in advance for your support.

**Comment by rntlqvnf** [comment]
I have same bug...

**Comment by Dudeplayz** [comment]
Hey, see #159.
