### ISSUE TITLE
Migrate to jooq 3.14

### ISSUE THREAD

**Issue by jklingsporn** [jklingsporn/vertx-jooq#166]

**Comment by Dudeplayz** [comment]
Hey, how are you dealing with kotlin support? I would really appreciate it because my projects are pure kotlin code.

**Comment by jklingsporn** [comment]
Until now, vertx-jooq only supports java. I don't really know much about kotlin so it will most probably stay like this.

**Comment by cubita-io** [comment]
Can Support JOOQ 3.14.8?

**Comment by jklingsporn** [comment]
If you provide this jooq dependency in your pom it should use it.

cubita <notifications@github.com> schrieb am Mo., 1. März 2021, 01:42:

**Comment by jklingsporn** [comment]
Released in version 6.2.0
