### ISSUE TITLE
How to pass `GENERATE_DATA_OBJECT_ANNOTATION` flag by gradle plugin ?

### ISSUE THREAD

**Issue by overstart** [jklingsporn/vertx-jooq#167]

**Comment by jklingsporn** [comment]
Unfortunately this is not possible out of the box. I am not very familiar with gradle so here I describe the maven way:
- create a new maven module with a dependency to `vertx-jooq-generate` 
- create a new class that extends `DelegatingVertxGenerator` like this
```
public class ClassicReactiveVertxGeneratorWithDataObjectSupport extends DelegatingVertxGenerator {

    public ClassicReactiveVertxGeneratorWithDataObjectSupport() {
        super(VertxGeneratorBuilder.init().withClassicAPI().withPostgresReactiveDriver().build(new BuildOptions().withBuildFlags(EnumSet.of(BuildOptions.BuildFlag.GENERATE_DATA_OBJECT_ANNOTATION))));
    }
}
```
- build the module 
- reference the new generator in your gradle plugin configuration
- note: the generated classes require a dependency to the `vertx-codegen`-module so make sure to add that to your dependency-configuration
