### ISSUE TITLE
I can't use the DAO in vertx-jooq-rx-reactive

### ISSUE THREAD

**Issue by JuanPalacios** [jklingsporn/vertx-jooq#168]
I am not be able to instanciate the SqlClient,  that the Dao is expecting, I received the following error:

java.lang.ClassCastException: class com.julienviet.pgclient.impl.PostgresClientImpl cannot be cast to class io.vertx.reactivex.sqlclient.SqlClient (com.julienviet.pgclient.impl.PostgresClientImpl and io.vertx.reactivex.sqlclient.SqlClient are in unnamed module of loader 'app')
	at com.example.starter.MainVerticle.handlerrequest(MainVerticle.java:58)
	at com.example.starter.MainVerticle.lambda$start$0(MainVerticle.java:35)

Could you help me to use the daos properly?

Thanks

**Comment by jklingsporn** [comment]
It looks like you still have a dependency to `com.julienviet.pgclient.impl.PostgresClientImpl` somewhere. Remove that and it should work.
