### ISSUE TITLE
Add `offset` option in `findManyByCondition` to support pagination.

### ISSUE THREAD

**Issue by leavestyle-jia** [jklingsporn/vertx-jooq#172]
I can't finish paging without `offset` param. Is there have a good resolving method?

**Comment by jklingsporn** [comment]
Hi, 
thanks for your message. Indeed, there is no such method yet but there is actually no reason to not have it (I wish Java had default method arguments). However, there is an easy workaround. If you look [here](https://github.com/jklingsporn/vertx-jooq/blob/master/vertx-jooq-shared/src/main/java/io/github/jklingsporn/vertx/jooq/shared/internal/AbstractVertxDAO.java#L82) it should be easy to implement it on your own:
```
dao.queryExecutor().findMany(selectQuery(condition).andThen(sel -> sel.limit(offset,limit)));
```

**Comment by LeaSty** [comment]
ok. Got it! Thanks

**Comment by LeaSty** [comment]
I think the ` limit ` fields, should add a ` offset ` field to match  😄

**Comment by jklingsporn** [comment]
Well not everybody needs `offset` so I will add a separate method.
