### ISSUE TITLE
How do batch update?

### ISSUE THREAD

**Issue by nikita-mtd** [jklingsporn/vertx-jooq#178]
Hi! Thx for realy good lib, but how i can batch update? Do i should use approach like generated dao's insert(collection) method?
'

**Comment by jklingsporn** [comment]
If you are just updating a single value per entity it might be best to craft a query using a `CASE ... WHEN`-statement as described here: https://stackoverflow.com/a/62879490/1033887 (paragraph **Running a single bulk statement**)

vertx-jooq does not support other native batch-operations from jOOQ.
