### ISSUE TITLE
Cursor support

### ISSUE THREAD

**Issue by cdekok** [jklingsporn/vertx-jooq#182]
Is it possible to fetchLazy or stream with the queryExecutor? I only found the methods to return ResultSets but for larger data sets it's sometimes required to use cursors.

https://www.jooq.org/doc/3.0/manual/sql-execution/fetching/lazy-fetching/
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/lazy-fetching-with-streams/

**Comment by jklingsporn** [comment]
I would advise you to use the reactive (postgres) driver and work as described [here](https://vertx.io/docs/vertx-pg-client/java/#_cursors_and_streaming). with jdbc, I am afraid this feature is not available in vertx-jooq.

**Comment by jklingsporn** [comment]
See also #116

**Comment by cdekok** [comment]
Ah yes I am using vertx, I didn't notice the other issue that had some useful info will close this as it's a duplicate.
