### ISSUE TITLE
When I want to change the generated table name and POJO name, then the DAO will not be generated

### ISSUE THREAD

**Issue by zhangruiyu** [jklingsporn/vertx-jooq#183]
When I want to change the generated table name and POJO name, then the DAO will not be generated
![image](https://user-images.githubusercontent.com/10591822/115383465-74ec1880-a208-11eb-93f8-6aed37b930ed.png)

**Comment by jklingsporn** [comment]
Hi,
I have provided my own `VertxGeneratorStrategy` at it works for me. For example at work I've created the following class (you can ignore the part with the `REMOVE_LAST_TWO_CHARS` set):
```
import io.github.jklingsporn.vertx.jooq.generate.VertxGeneratorStrategy;
import org.jooq.codegen.GeneratorStrategy;
import org.jooq.meta.Definition;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

public class AsInDbGeneratorStrategy extends VertxGeneratorStrategy {

    @Override
    public String getJavaGetterName(Definition definition, GeneratorStrategy.Mode mode) {
        return "get" + definitionToName(definition,false);
    }

    @Override
    public String getJavaSetterName(Definition definition, GeneratorStrategy.Mode mode) {
        return "set" + definitionToName(definition,false);
    }

    @Override
    public String getJavaClassName(Definition definition, GeneratorStrategy.Mode mode) {
        String newName = definitionToName(definition,true);
        switch(mode){
            case DAO:
                return newName+"Dao";
            case DEFAULT:
            case ENUM:
            case POJO:
                return newName;
            case INTERFACE:
                return "I"+newName;
            case RECORD:
                return newName+"Record";
            default:
                return super.getJavaClassName(definition,mode);
        }
    }

    private static Set<String> REMOVE_LAST_TWO_CHARS = new HashSet<>(Arrays.asList("matches","usermatches"));
    private String definitionToName(Definition definition, boolean removeTheS) {
        String name = Arrays.stream(definition.getName().split("_"))
                .map(s -> s.substring(0, 1).toUpperCase().concat(s.substring(1)))
                .collect(Collectors.joining());
        if(removeTheS && name.endsWith("ies")){
            return name.substring(0,name.length() - 3)+"y";
        }else if(removeTheS && name.endsWith("s")){
            //remove s
            return name.substring(0,name.length() - (REMOVE_LAST_TWO_CHARS.contains(name.toLowerCase())?2:1));
        }
        return name;
    }

    @Override
    public String getFullJavaClassName(Definition definition, GeneratorStrategy.Mode mode) {
        return super.getFullJavaClassName(definition, mode);
    }
}
```
If the class is defined in the same module that is generating the code, you must build the class that contains the generator first. In my case, we had a maven multi-module setup like this:
- app-jooq-module
  - contains `AsInDbGeneratorStrategy`
- app-generator-module
  - pom configured with the `jooq-codegen-maven`-plugin
    - configured with `AsInDbGeneratorStrategy` under `configuration` -> `generator` -> `strategy`
  - dependency to  app-jooq-module
You would then navigate to `app-jooq-module` and run `mvn clean install` to build the `AsInDbGeneratorStrategy` and put it into the local maven repository, so the `jooq-codegen-maven`-plugin would find it.

**Comment by zhangruiyu** [comment]
> Hi,
> I have provided my own and it works for me. For example at work I've created the following class (you can ignore the part with the set):`VertxGeneratorStrategy``REMOVE_LAST_TWO_CHARS`
> 
> ```
> import io.github.jklingsporn.vertx.jooq.generate.VertxGeneratorStrategy;
> import org.jooq.codegen.GeneratorStrategy;
> import org.jooq.meta.Definition;
> 
> import java.util.Arrays;
> import java.util.HashSet;
> import java.util.Set;
> import java.util.stream.Collectors;
> 
> public class AsInDbGeneratorStrategy extends VertxGeneratorStrategy {
> 
>     @Override
>     public String getJavaGetterName(Definition definition, GeneratorStrategy.Mode mode) {
>         return "get" + definitionToName(definition,false);
>     }
> 
>     @Override
>     public String getJavaSetterName(Definition definition, GeneratorStrategy.Mode mode) {
>         return "set" + definitionToName(definition,false);
>     }
> 
>     @Override
>     public String getJavaClassName(Definition definition, GeneratorStrategy.Mode mode) {
>         String newName = definitionToName(definition,true);
>         switch(mode){
>             case DAO:
>                 return newName+"Dao";
>             case DEFAULT:
>             case ENUM:
>             case POJO:
>                 return newName;
>             case INTERFACE:
>                 return "I"+newName;
>             case RECORD:
>                 return newName+"Record";
>             default:
>                 return super.getJavaClassName(definition,mode);
>         }
>     }
> 
>     private static Set<String> REMOVE_LAST_TWO_CHARS = new HashSet<>(Arrays.asList("matches","usermatches"));
>     private String definitionToName(Definition definition, boolean removeTheS) {
>         String name = Arrays.stream(definition.getName().split("_"))
>                 .map(s -> s.substring(0, 1).toUpperCase().concat(s.substring(1)))
>                 .collect(Collectors.joining());
>         if(removeTheS && name.endsWith("ies")){
>             return name.substring(0,name.length() - 3)+"y";
>         }else if(removeTheS && name.endsWith("s")){
>             //remove s
>             return name.substring(0,name.length() - (REMOVE_LAST_TWO_CHARS.contains(name.toLowerCase())?2:1));
>         }
>         return name;
>     }
> 
>     @Override
>     public String getFullJavaClassName(Definition definition, GeneratorStrategy.Mode mode) {
>         return super.getFullJavaClassName(definition, mode);
>     }
> }
> ```
> 
> If the class is defined in the same module that is generating the code, you must build the class that contains the generator first. In my case, we had a maven multi-module setup like this:
> 
> * app-jooq-module
>   
>   * contains `AsInDbGeneratorStrategy`
> * app-generator-module
>   
>   * pom configured with the -plugin
>     `jooq-codegen-maven`
>     * configured with  under `AsInDbGeneratorStrategy``configuration` -> `generator` -> `strategy`
>   * dependency to  app-jooq-module
> 
> You would then navigate to and run to build the and put it into the local maven repository, so the -plugin would find it.`app-jooq-module``mvn clean install``AsInDbGeneratorStrategy``jooq-codegen-maven`

Wow, thank you very much
