### ISSUE TITLE
RXJava streaming support

### ISSUE THREAD

**Issue by Jotschi** [jklingsporn/vertx-jooq#184]
Is it possible to utilize rxjava result streams from vertx sql clients with vertx-jooq?
See https://vertx.io/docs/vertx-pg-client/java/#_streaming

So far I have been able to return `Single<List<POJO>>`. I would however prefer `Observable<POJO>` instead.
I know that I can transform the list and that is actually my current solution but I'd rather stream the data to conserve memory.

**Comment by jklingsporn** [comment]
Hi @Jotschi ,
I think your issue is related / duplicated by [this issue](https://github.com/jklingsporn/vertx-jooq/issues/116). Please re-open if I am mistaken.
Regards,
Jens

**Comment by Jotschi** [comment]
@jklingsporn You are right. Thanks for the info.
