### ISSUE TITLE
Can I use log4j2 instead of log4j?

### ISSUE THREAD

**Issue by chenmaochang** [jklingsporn/vertx-jooq#192]
I config a logger extends DefaultExecuteListener and set it with  Jooq Configuration, but it dont work.

**Comment by romanbsd** [comment]
There're two loggers used in different scenarios, one is Vertx logger and another is Jooq logger. For the latter see implementation https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/tools/JooqLogger.java

**Comment by jklingsporn** [comment]
Yeah, this question is not related to vertx-jooq. Please consult the official logs: https://www.jooq.org/doc/3.15/manual/sql-execution/logging/

**Comment by chenmaochang** [comment]
got it
