### ISSUE TITLE
Support for commercial JOOQ

### ISSUE THREAD

**Issue by bhrt-DS** [jklingsporn/vertx-jooq#200]
Hello,

We are planning to migrate our legacy microservice to vertx. As our existing microservice has oracle DB, we require commercial JOOQ integration. Regarding to this I have few questions,

1. Does vertx-jooq-classic-jdbc is compatible with commercial JOOQ?
2. if Yes, Do we have any documentation available for same?
3. if No, Any future plan to provide support?

Thanks

**Comment by jklingsporn** [comment]
Hi,

1. The commercial distribution has it's own maven-dependency identifier and I don't think the commercial and open source version can live side-by-side.
2. see above
3. Not really, but I'm happy to accept PRs in that matter or suggestions of how to solve this issue.

**Comment by jklingsporn** [comment]
I think the best way for you to overcome this issue is by forking this project and replace the standard-dependencies with the commercial ones: https://www.jooq.org/doc/3.16/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/

Since you have to provide the commercial jOOQ artifacts on your own it shouldn't be too hard to do the same with your forked commercial-vertx-jooq.
HTH

**Comment by bhrt-DS** [comment]
Thank you so much @jklingsporn for quick reply. This is helpful information. 
Since goal of this ticket was to get information only. So, based on above information, closing this issue.

**Comment by bhrt-DS** [comment]
Hey @jklingsporn,

I did some further research on above topic. i.e. How we can introduce commercial version of JOOQ in open source library. Regarding to this, I found an open source [JOOQ gradle plugin](https://github.com/etiennestuder/gradle-jooq-plugin), who supports commercial JOOQ versions. This library uses [editions](https://github.com/etiennestuder/gradle-jooq-plugin/blob/master/src/main/groovy/nu/studer/gradle/jooq/JooqEdition.java) as a input to achieve that. So, we can introduce something similar here.

I also have one question which I missed to ask earlier,
I know we can use vertx-jooq with Postgres fluently. Similarly, can we use vertx-jooq with oracle database? Do you see any challenges apart from commercial version use? I'm planning to create below setup for my service,

- **Database connectivity** - vertx-jooq-classic-jdbc with oracle database
- **Code generation** - ClassicJDBCVertxGenerator with oracle drivers

**Comment by jklingsporn** [comment]
1. I don't see any problems with using `vertx-jooq-classic-jdbc` with orcale as long as you provide the drivers and of course manage the `jooq-pro` dependency for code generation.
2. Having said that, I don't plan to add pro-versions of `vertx-jooq`. The main reason is that I'd need myself pro-dependencies for my integration tests. On top of that, `vertx-jooq` is open source and I don't want that to be mixed with closed source / commercial licenses.
