### ISSUE TITLE
JDK17:  reference to Record is ambiguous

### ISSUE THREAD

**Issue by silentbalanceyh** [jklingsporn/vertx-jooq#212]
I'm not sure if this issue is related to Jooq-codegen ( 3.17.3 ) or ( vertx-jooq-generate 6.5.5 ), the template resolution is following:

From

```java
import org.jooq.*;
```

To

```java
import org.jooq.Record;
import org.jooq.*;
```

I want to know more details and upgrading plan of current project.

**Comment by jklingsporn** [comment]
Not sure if I understand correctly. I've been using vertx-jooq 6.5.5 with java 17 (and records). What is your issue?

**Comment by silentbalanceyh** [comment]
You can close this issue now, It's conflict between JDK Record and jooq Record, I did refactor of my projects.
