### ISSUE TITLE
the generated code appear compile error

### ISSUE THREAD

**Issue by dreamkidd** [jklingsporn/vertx-jooq#27]
the dao class got `there is no default constructor avaliable in 'org.jooq.impl.DAOImpl'`

and the pojo class has a default method in Pojo Class

just like this 
```java
default ISysUser fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getInteger("id"));
        setUserName(json.getString("user_name"));
 ...
    }
```

i wonder know what can cause this

**Comment by jklingsporn** [comment]
Do you have set any specific flags for the code generator?

**Comment by dreamkidd** [comment]
No,i didn't specific any flag for the code generator
i just specified generate which like readme.md via gradle

**Comment by jklingsporn** [comment]
I think I've found the issue: if the `interfaces` flag is set to `false` in the generator, the generated POJO has default methods. For now: can you try setting the flag to `true`?

**Comment by jklingsporn** [comment]
I've created a fix for this issue in this branch: https://github.com/jklingsporn/vertx-jooq/tree/release2.4.2

**Comment by dreamkidd** [comment]
thanks it could generate the normal code
