### ISSUE TITLE
class AsyncJooqSQLClient missing

### ISSUE THREAD

**Issue by dlkw** [jklingsporn/vertx-jooq#30]
The `usage` section at the end of the `Readme.md` in vertx-jooq-classic-async lists
```java
AsyncJooqSQLClient client = AsyncJooqSQLClient.create(vertx,MySQLClient.createNonShared(vertx, config))
```
but I cannot find class `AsyncJooqSQLClient` anywhere.

This might be either a bug in the docs or an omission due to the move from the separate async repository into this repository.

**Comment by jklingsporn** [comment]
Thanks for the comment. This was a copy-paste mistake. It should be rather `AsyncSQLClient client = MySQLClient.createNonShared(vertx, config);`.

**Comment by jklingsporn** [comment]
fixed
