### ISSUE TITLE
compilation fails when interfaces generation is set to false

### ISSUE THREAD

**Issue by kirillkh** [jklingsporn/vertx-jooq#37]
VertxGenerator.generateFromJson() and generateToJson() unconditionally calls out.override(), which causes @Override annotations to be output for pojos and records, even though they override nothing when interfaces generation is set to false, which causes compilation errors.

**Comment by jklingsporn** [comment]
Thanks for the report. I'll look into it.

Am 03.03.2018 6:05 nachm. schrieb "Kirill Khazan" <notifications@github.com

**Comment by jklingsporn** [comment]
fixed
