### ISSUE TITLE
Create complex request

### ISSUE THREAD

**Issue by quen2404** [jklingsporn/vertx-jooq#48]
Hi,
it should be nice if we could use dao to make complex requests like `group by`, or `join`. Because, currently we have to redevelop the wrapper between JooQ and sql driver.
What do you think ?

**Comment by jklingsporn** [comment]
I've been working on the 4.0 version the last couple of weeks which includes a new interface for the `QueryExecutor` so one can execute arbitrary jOOQ-SQL on any driver with a unified API for the returned value. I'm planning to release a alpha-version during the next days so maybe you can give me some feedback.
My main concern about incorporating this into the DAO is that DAO's are bound to a POJO and thus shouldn't break boundaries by altering other tables. 
Or do you already have an API in mind?

**Comment by quen2404** [comment]
Oh really ? It's a good news ! 
Yes, no problem to give you some feedback.
No I don't have a concrete idea about how implement that, but i'm agree with you, currently DAO's are linked to POJO and UpdatableRecord. So this kind of feature should be splited from DAO.
I'm excited to see this new API 👍

**Comment by jklingsporn** [comment]
You cannot have transactions for dao operations. You have to explicitly invoke `dslcontext.transaction()` and write the queries by hand.

**Comment by jklingsporn** [comment]
You can read about the new API here: https://github.com/jklingsporn/vertx-jooq/tree/release4.0.0

**Comment by quen2404** [comment]
Thank you, i will take a look this weekend :)

**Comment by quen2404** [comment]
I made a custom query executor which use driver transaction. Does it interest you ?
