### ISSUE TITLE
Unrecognized types: UUID, LocalDate, smallint etc.

### ISSUE THREAD

**Issue by paninics** [jklingsporn/vertx-jooq#57]
I'm using the 4.0-beta version and am getting a bunch of these warnings:

```
[INFO] Generating POJO          : Address.java
[WARNING] Omitting unrecognized type java.util.UUID for column customerId in table Address!
[WARNING] Omitting unrecognized type java.time.LocalDate for column birthDate in table Child!
	
[INFO] Generate RowMappers ...  
[WARNING] Omitting unrecognized type DataType [ t=smallint; p=16; s=0; u="pg_catalog"."int2"; j=null ] (java.lang.Short) for column countryId in table Address!
```
To partially workaround the POJO warnings, I wrote a custom `CodeGenerator` that extends `RXReactiveVertxGenerator` to handle the custom types - This is same as what I'd in 3.0 version. So two questions:

1. Aren't these types supposed to be handled (in 4.0 version) by the generator given that the default jooq generator handles it? Further, I see that these types are also supported by the `reactive-pg-client`. 

2. What workaround do I need to implement about the `smallint` datatype warning when the `RowMappers` are generated?

**Comment by jklingsporn** [comment]
1. `UUID` and `LocalDate` are no valid `io.vertx.core.json.JsonObject` types - so they are omitted by default.
2. At the time of writing, the `reactive-pg-client` did not support `short`. I'll add it.

**Comment by jklingsporn** [comment]
Yeah, one could automatically convert those types to `String` in the `from/toJson` methods.

**Comment by abonander** [comment]
@jklingsporn you closed this in f29dcf4 but you only really addressed `short`. 

Both `UUID` and the time types have string conversions, which are technically fallible but if they're only being converted by `fromJson()` and `toJson()` then they should always be in valid forms. Do you just not want the possibility of `fromJson()` throwing on invalid inputs?

**Comment by InfoSec812** [comment]
I'm running up against this problem in `6.3.0` and PostgreSQL. The generated code is using a `byte[]` in place of the UUID. but I cannot use a `byte[]` as the search param in `findOneById()`.

**Comment by InfoSec812** [comment]
Again, disregard... I was able to work around this using a converter as explained here: https://www.jooq.org/doc/3.1/manual/code-generation/custom-data-types/
