### ISSUE TITLE
ArrayIndexOutOfBoundsException when using custom code generator strategy

### ISSUE THREAD

**Issue by paninics** [jklingsporn/vertx-jooq#58]
I'm using the 4.0-beta version. If I have a custom code generator strategy, attached, I get the following error:

```
[ERROR] Error while generating table DAO public.<table name>
java.lang.ArrayIndexOutOfBoundsException: 1
	at io.github.jklingsporn.vertx.jooq.generate.builder.VertxGeneratorBuilder$ExecutionStepImpl.lambda$withPostgresReactiveDriver$30(VertxGeneratorBuilder.java:378)
	at io.github.jklingsporn.vertx.jooq.generate.builder.ComponentBasedVertxGenerator.writeDAOConstructor(ComponentBasedVertxGenerator.java:81)
	at io.github.jklingsporn.vertx.jooq.generate.builder.DelegatingVertxGenerator.writeDAOConstructor(DelegatingVertxGenerator.java:63)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDAO(VertxGenerator.java:542)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDao(VertxGenerator.java:479)
	at org.jooq.util.JavaGenerator.generateDao(JavaGenerator.java:2742)
	at org.jooq.util.JavaGenerator.generateDaos(JavaGenerator.java:2729)
	at io.github.jklingsporn.vertx.jooq.generate.VertxGenerator.generateDaos(VertxGenerator.java:231)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:459)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:405)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:327)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:647)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
```
Upon further debugging, it appears that the code is expecting fully qualified class name (`at VertxGeneratorBuilder, lines 377-378`) where as the actual value is just the class name i.e. without the package name. The custom code generator strategy is as is from the 3.0 version and worked fine. So something is going wrong in the 4.0-beta version. Could it be that the entire code base expects the string `"pojos"` but the package names that is provided by the custom code generator strategy is `"pojo"`? As an experiment, I did try to switch to `"pojos"` in the custom code but that didn't help. 

[CodeGeneratorStrategy.zip](https://github.com/jklingsporn/vertx-jooq/files/2078526/CodeGeneratorStrategy.zip)

**Comment by jklingsporn** [comment]
Thank you very much for your bugreport. Indeed the code for now requires `pType` to contain  the string `pojos.` which is not very smart. I'll change it so it splits by `.` and takes the last part of the result.

**Comment by jklingsporn** [comment]
Upon further investigation the existing solution totally makes sense - unless you explicitly omit `pojos` from generation which doesn't make sense.

**Comment by jklingsporn** [comment]
I've looked into your generator. Any reason why you're overriding `getJavaPackageName`? There is a configuration property for the code generator called `targetPackage`, see also https://www.jooq.org/doc/3.10/manual/code-generation/codegen-advanced/codegen-config-target/
So my suggestion is to delete that method and set `targetPackage` to `com.el.db`.

**Comment by paninics** [comment]
Incidentally, I did have the package name set in the configuration file as well - Must have been a leftover after I overrode the `getJavaPackageName` method. I also tried your suggestion of deleting this method and still get the `ArrayIndexOutOfBoundsException` error. The `pojos` are indeed being generated. The error happens during `DAO` generation.

To answer your other question, I chose to override the method because of internal naming conventions that discourages using plural forms eg. `pojo` instead of `pojos`. Regardless, JOOQ documentation that you've pointed also states that a custom implementation can be provided. And you never know what the motivation might be of each developer who chooses to override. Hence IMHO the code should handle it seamlessly, which was the case in 3.0 version.

**Comment by jklingsporn** [comment]
I guess you're right. I've modified the code now so it takes modifications made by custom `GeneratorStrategies` into account. On top of that, I've added a possibility to define the sub-package name for the generated `RowMappers`.

**Comment by paninics** [comment]
Thank you. I looked at the commit and see some limitations.

```java 
out.println("package " + base.getActiveGenerator().getStrategy().getJavaPackageName(schema) 
            + ".tables."+mappersSubPackage+";");
```

In the above code, the package name is effectively hard coded as we're concatenating `"tables"`. Instead the code should call `getJavaPackageName(tableDefinition)` or something along those lines so that we directly get the table's package namespace. I would actually go one step even further and generalize it, if it can be done. Let us not make any hard choices of what the mapper's package namespace is. It may be a sub package of `tables` or it could be something else. Leave that decision to the generator strategy, if one is provided - something along these lines: 

```java
String mapperPackage = getMapperPackage(); // Get value from generator strategy
if (mapperPackage == null || mapperPackage == "") {
   mapperPackage = base.getActiveGenerator().getStrategy().getJavaPackageName(schema) 
      + ".tables.mappers";
} 
out.println("package " + mapperPackage + ";");
```

**Comment by paninics** [comment]
The 4.0 code is still generating the `RowMappers.java` in the `tables` package instead of using the value returned by the `getJavaPackageName()`. This is because "tables" is still hard coded and the value returned by `getRowMappersSubPackage()` becomes moot. E.g. Lines [279](https://github.com/jklingsporn/vertx-jooq/blob/e1e6cdcbad523b21ae9f9904f672a65a0f909448/vertx-jooq-generate/src/main/java/io/github/jklingsporn/vertx/jooq/generate/builder/VertxGeneratorBuilder.java#L279), 285, 456 and 459 in `VertxGeneratorBuilder.java`. Hence kindly re-open the issue.
