### ISSUE TITLE
RowMappers.java created in different directory 

### ISSUE THREAD

**Issue by paninics** [jklingsporn/vertx-jooq#59]
Using 4.0-beta along with `VertxGeneratorStrategy` for code generation. The code executes fine but when I look at the generated DAO code, I see a reference to `org.jooq.generated.tables.mappers.RowMappers` class in the DAO constructor, which is missing. Upon debugging, I see that the class is being generated but in a different directory instead of honoring the target directory (relative path in my case `"../generated/src/main/java"`) as specified in the configuration file - https://www.jooq.org/doc/3.10/manual/code-generation/codegen-advanced/codegen-config-target/. To be clear all other files (pojos, daos etc.) are being generated in the specified target directory. It's only the `RowMappers.java` that is not. I suspect the relative path is tripping the code during initialization of the target directory.

**Comment by paninics** [comment]
FYI - After a bit of debugging, I modified `VertxGeneratorBuilder.withPostgresReactiveDriver()` to handle relative paths as shown below.

```java
ComponentBasedVertxGenerator.logger.info("Generate RowMappers ... ");
String packageName = base.getActiveGenerator().getStrategy().getJavaPackageName(schema) + ".tables.mappers";
String dir = base.getActiveGenerator().getStrategy().getTargetDirectory()
		+ "/" + packageName.replaceAll("\\.", "/");
try {
	File f = new File(dir).getCanonicalFile();
	dir = f.getCanonicalPath();
	if (! f.mkdir()) {
		ComponentBasedVertxGenerator.logger.warn("Failed to create directory " + dir);
	}
} catch (IOException e) {
	ComponentBasedVertxGenerator.logger.warn(e);
}
File moduleFile = new File(dir, "RowMappers.java");

JavaWriter out = writerGen.apply(moduleFile);
out.println("package " + packageName + ";");
```
As a result the `RowMappers.java` file was generated. However it disappeared at the end of code generation. Upon further debugging, I found that there's a cleanup code in `org.jooq.util.JavaGenerator.generate()` lines 338-340 that deletes excess files. So somehow we've to flag to this code that this directory or file should not be deleted.

**Comment by paninics** [comment]
Finally I got it working with further digging around. Here's the workaround:

```java
ComponentBasedVertxGenerator.logger.info("Generate RowMappers ... ");
String packageName = base.getActiveGenerator().getStrategy().getJavaPackageName(schema) + ".tables.mappers";
String dir = base.getActiveGenerator().getStrategy().getTargetDirectory();
dir = File.separator.equals("/") ? dir.replace("\\", File.separator) : dir.replace("/", File.separator);
dir = dir + File.separator + packageName.replace(".", File.separator);
File moduleFile = new File(dir, "RowMappers.java");
JavaWriter out = writerGen.apply(moduleFile);
out.println("package " + packageName + ";");
```
It was the canonical path in the earlier code that resulted in different file path strings that the cleanup code saw. All other paths looked like `C:\Users\foo\development\codegen\..\generated\src\main\java\org\jooq\generated\xxx.java`. However, with the canonical path, the ".." was resolved and hence it was an absolute path. The above code matches the pattern with other paths. Personally I feel this is a hack. Instead I think this is what is needed - After reading the target directory from the configuration file, resolve it to a canonical path and then call the `GeneratorStrategy.setTargetDirectory()` with the canonical path. Then all subsequent code can leverage the right value without the above hacks. So the right place for such a code seems to be in `org.jooq.util.GenerationTool.run()` line 523, which the JOOQ author(s) should look at.

**Comment by jklingsporn** [comment]
That is a strange behavior indeed. Especially because I'm generating code with version `4.0.0-Beta` in the tests plus in projects depending on vertx-jooq.
Can you share the configuration you are using? Also if you're doing it programmatically or using maven configuration.

**Comment by paninics** [comment]
Here's what I've in Maven i.e. basically pointer to the external configuration file.

```xml
<!-- jooq configuration -->
<configuration>
	<configurationFile>src/main/conf/jooq-pg.xml</configurationFile>
</configuration>
```

And here's my jooq configuration, omitted the `<jdbc>` section. The custom generator strategy code is attached in issue #58

```xml
<generator>
	<name>io.github.jklingsporn.vertx.jooq.generate.rx.RXReactiveVertxGenerator</name>
	<database>
		<name>org.jooq.util.postgres.PostgresDatabase</name>
		<includes>.*</includes>
		<excludes>
			UNUSED_TABLE # This table (unqualified name) should not be generated
			| PREFIX_.* # Objects with a given prefix should not be generated
			| SECRET_SCHEMA\.SECRET_TABLE # This table (qualified name) should not be generated
			| SECRET_ROUTINE # This routine (unqualified name) ...
		</excludes>
		<inputSchema>public</inputSchema>
		<unsignedTypes>false</unsignedTypes>
		<forcedTypes>
			<!--Convert varchar column with name 'someJsonObject' to a io.vertx.core.json.JsonObject-->
			<forcedType>
				<userType>io.vertx.core.json.JsonObject</userType>
				<converter>io.github.jklingsporn.vertx.jooq.shared.JsonObjectConverter</converter>
				<expression>someJsonObject</expression>
				<types>.*</types>
			</forcedType>
			<!--Convert varchar column with name 'someJsonArray' to a io.vertx.core.json.JsonArray-->
			<forcedType>
				<userType>io.vertx.core.json.JsonArray</userType>
				<converter>io.github.jklingsporn.vertx.jooq.shared.JsonArrayConverter</converter>
				<expression>someJsonArray</expression>
				<types>.*</types>
			</forcedType>
		</forcedTypes>
	</database>
	<generate>
		<!-- Generation flags: See advanced configuration properties -->
		<javaTimeTypes>true</javaTimeTypes>
		<daos>true</daos>
		<fluentSetters>true</fluentSetters>
	</generate>
	<strategy>
		<name>com.el.db.jooq.CodeGeneratorStrategy</name>
		<!--<name>io.github.jklingsporn.vertx.jooq.generate.VertxGeneratorStrategy</name>-->
	</strategy>

	<target>
		<directory>../generated/src/main/java</directory>
	</target>
</generator>
```

**Comment by jklingsporn** [comment]
Thanks for your help. I've added your snippet 
```
ComponentBasedVertxGenerator.logger.info("Generate RowMappers ... ");
String packageName = base.getActiveGenerator().getStrategy().getJavaPackageName(schema) + ".tables.mappers";
String dir = base.getActiveGenerator().getStrategy().getTargetDirectory();
dir = File.separator.equals("/") ? dir.replace("\\", File.separator) : dir.replace("/", File.separator);
dir = dir + File.separator + packageName.replace(".", File.separator);
File moduleFile = new File(dir, "RowMappers.java");
JavaWriter out = writerGen.apply(moduleFile);
out.println("package " + packageName + ";");
```
with minor modifications. I'll draft a release once I've figured out why the latest pg-client has dropped support for `JsonObject` ;)

**Comment by paninics** [comment]
Thank you. But as I pointed out this truly a hack. While the code works for the scenario that I've it is still very fragile. E.g. What if the target directory ends with a slash e.g. `"../generated/src/main/java/"`. Now see the value of `dir` as the execution progresses. To avoid such pitfalls, we should avoid using file separators at all cost. Instead we should start with a canonical path and then use the `File(dir, child)` constructors where required. Hence my recommendation to bring this up with the jooq author(s). If that's a stretch or if it cannot be done for whatever reason, then perhaps consider to reset the target directory with a canonical path from your end before the code generation begins,
