### ISSUE TITLE
Retrieve auto-incremented primary key after insert

### ISSUE THREAD

**Issue by schuma7** [jklingsporn/vertx-jooq#60]
I am using vertx-jooq-classic-async with PostgreSQL. I'm currently looking for a way to retrieve the primary key of a newly inserted row.

I first attempted to do this by using the AsyncClassicGenericQueryExecutor. However, it seems as the query executor only returns the number of affected rows.

I then tried to use the insertReturningPrimary method of the corresponding DAO. However, this feature is currently not supported for PostgreSQL.

Normally, I'd just use the generated Record class to insert a new entity, due to the fact that the id field of the record is updated after the insert. However, it doesn't seem as if Records are supported, since there is no way to provide a client connection.

Am I missing something or is it currently not possible to retrieve the primary key when using PostgreSQL?

**Comment by jklingsporn** [comment]
Yes, this is currently not supported but will be in the next release. The beta has already been released: https://github.com/jklingsporn/vertx-jooq/tree/release4.0.0

**Comment by schuma7** [comment]
Looks like a pretty cool upgrade! Do you already have a rough release date you're aiming for?

**Comment by jklingsporn** [comment]
I haven't tried this yet, but it should work.

**Comment by schuma7** [comment]
It doesn't work, since the query method expects a ResultQuery while the insert statement returns a InsertResultStep which inherits from Query.

**Comment by jklingsporn** [comment]
Thank you for looking into this. If you have any idea how to circumvent this, I'd really appreciate contributions of any kind. Unfortunately I'm very busy doing other stuff...

**Comment by schuma7** [comment]
I'm afraid I won't have the time to dig into this either at the moment. I will close this issue, since I was able to retrieve the new primary key using the DAO's insertReturningPrimary method as available in the 4.0.0-BETA branch.

Looking forward to the actual release. Thank you for your help.
