### ISSUE TITLE
Offsetdatetime to Joda conversion breaks on ISO8601 timestamp with timezone "Z"

### ISSUE THREAD

**Issue by m1schka** [jklingsporn/vertx-jooq#64]
as found through #63, in `AbstractAsyncQueryExecutor`, the code `DateTimeZone.forID(convert.getZone().getId())` breaks when using a valid ISO8601 timestamp with a timezone set to UTC through `Z` (e.g `2018-06-11T15:36:43.349Z`).

the result is an IllegalArgumentException: `The datetime zone id 'Z' is not recognised`

**Comment by m1schka** [comment]
Even when using proper zone offsets, the code breaks. 

`ZonedDateTime convert = obj.atZoneSameInstant(ZoneOffset.UTC);` seems to be the problem after investigation, see screenshot
<img width="568" alt="screen shot 2018-06-27 at 10 53 48" src="https://user-images.githubusercontent.com/1403301/41963754-ab8249cc-79f8-11e8-93ab-543cd70e488f.png">

**Comment by jklingsporn** [comment]
If you have the time, feel free to provide a fix for this.
