### ISSUE TITLE
Support for Jooq ActiveRecords

### ISSUE THREAD

**Issue by sowmyark** [jklingsporn/vertx-jooq#82]
Does the Vertx Jooq Reactive module support the ActiveRecord feature of Jooq. We would like to do CRUD with UpdatableRecord with optimistic locking. If we use the UpdatableRecord methods (store, refresh etc) will it internally use the reactive pg api?

**Comment by jklingsporn** [comment]
Unfortunately no.

Am Mi., 5. Dez. 2018, 08:17 hat sowmyark <notifications@github.com>
geschrieben:

**Comment by sowmyark** [comment]
Thanks for you quick reply. 
Do you have any plans of supporting this in the near future? 
Also we would like to understand the complexity involved in implementing this with the reactive pg api so that we can give it a try. Could you give us some starting pointers for this.

**Comment by jklingsporn** [comment]
I think it is nearly impossible. For example when you call `store` on an `ActiveRecord` it automatically calls the blocking jdbc method equivalent. 
To really implement non-blocking CRUD for Records you'd have to overwrite the `generateRecord` method in the `JavaGenerator/VertxGenerator` and add an async API for records (like I did with the `VertxDao`).
