### ISSUE TITLE
vertx-jooq-classic VertxDao methods are deprecated

### ISSUE THREAD

**Issue by nileshkemse** [jklingsporn/vertx-jooq#85]
I was using vertx-jooq-classic 2.4.1. but in latest version i.e 4.0.0 all methods in VertxDao I was using seems to be depecrated. Any alternative that you have provided?

**Comment by dhoffer** [comment]
Why was this closed w/o comment?  We too are using 2.4.1 and would like to know how this works with later versions.

**Comment by nileshkemse** [comment]
Hi dhoffer,
Sorry for closing this without comment. I have started using latest version and found that daos methods are deprecated. However they have provided new classic executer with which you can achieve the same. You can get it by the doc. Let me know if you get any problem
