### ISSUE TITLE
Would you consider replacing mauricio driver which is not supported anymore

### ISSUE THREAD

**Issue by oshai** [jklingsporn/vertx-jooq#91]
We are supporting a fork called jasync-sql that is also used by vertex: https://github.com/vert-x3/vertx-mysql-postgresql-client.   
Will you consider adding it or replacing mauricio driver? It is mostly compatible with the following changes: https://github.com/jasync-sql/jasync-sql/wiki/Mauricio-Driver-Migration

**Comment by oshai** [comment]
I can provide a PR if you would like that.

**Comment by jklingsporn** [comment]
Hello and thank you for your request. Indeed I was just looking into transaction support for vertx-jooq and how it was implemented in mauricio's driver and then figured out that the project is no longer maintained. 
On the other hand it is still part of the official [vertx-stack](https://vertx.io/docs/vertx-mysql-postgresql-client/java/) which vertx-jooq is also using. 
I can imagine vertx community will drop support for the async driver in vertx 4 but until then I'm afraid I will stick to mauricio's driver.

**Comment by oshai** [comment]
As you can see from the link I sent above it is being replaced by jasync. Probably since 3.6.3 was not released yet they did not update that site.

**Comment by oshai** [comment]
Great!

**Comment by jklingsporn** [comment]
Unfortunately the driver didn't made it into vertx 3.6.3 so this update has to be postponed.

**Comment by oshai** [comment]
well, that is not accurate. docs are not in place yet but the artifact was created for 3.6.3: https://mvnrepository.com/artifact/io.vertx/vertx-mysql-postgresql-client-jasync

**Comment by jklingsporn** [comment]
Fixed in https://github.com/jklingsporn/vertx-jooq/tree/release4.1.0

**Comment by oshai** [comment]
Thanks!
