### ISSUE TITLE
Looking for reactive ORM

### ISSUE THREAD

**Issue by ORESoftware** [jklingsporn/vertx-jooq#94]
this looks cool as far as I can tell:
https://github.com/jklingsporn/vertx-jooq/tree/master/vertx-jooq-classic-reactive

but I am really looking for an ORM, especially to help out with db migrations and basic validation etc.

I guess I don't know the advantages of using JOOQ vs just using code like so:

```java
     conn.query("SELECT * FROM account", results -> {
        
        if (!results.succeeded()) {
          throw new Error("Could not connect.");
        }
        
        ResultSet rs = results.result();
        System.out.println("Connected and got results");
        System.out.println(rs.toString());
        
      });
```

I am interested in using this lib just newb needs some guidance thanks

**Comment by haposan06** [comment]
> Ok so after a little more due diligence, JOOQ allows us to do things like:
> 
> https://www.jooq.org/doc/3.1/manual/sql-building/sql-statements/select-statement/
> 
> but I am still looking for a way to model db tables with POJOs and get muh migration and validation on somehow for each model, plus your joins (belongs to, etc) and things like that too.

You could look into this documentation https://www.jooq.org/doc/3.1/manual/code-generation/

**Comment by jklingsporn** [comment]
If you have further questions regarding `vertx-jooq` feel free to ask. Other than that please refer to the official [jooq-documentation](https://www.jooq.org/doc/3.11/manual/).
