### ISSUE TITLE
vertx-jooq-rx-reactive: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by paninics** [jklingsporn/vertx-jooq#98]
I've a simple piece of code:
```java
// qe is ReactiveRXGenericQueryExecutor
// emptyId is a non-existing id in database
qe.query(db -> db.selectFrom(Tables.CUSTOMER).where(Tables.CUSTOMER.CUSTOMER_ID.eq(emptyId))).subscribe(x -> {
	if (x.hasResults()) {
		System.out.println("has result");
	} else {
		System.out.println("no result");
	}
});
```

The expected output is "no result" but instead get the following error:
```java
Caused by: java.util.NoSuchElementException
	at io.reactiverse.pgclient.impl.PgRowSetImpl$1.next(PgRowSetImpl.java:64)
	at io.github.jklingsporn.vertx.jooq.shared.reactive.ReactiveQueryResult.<init>(ReactiveQueryResult.java:24)
	at io.github.jklingsporn.vertx.jooq.rx.reactivepg.ReactiveRXGenericQueryExecutor.lambda$query$2(ReactiveRXGenericQueryExecutor.java:85)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
```

Upon further debugging, it appears to me the [code in the constructor](https://github.com/jklingsporn/vertx-jooq/blob/66ddf381e9e468cc263aad4cc93516549f014ae5/vertx-jooq-shared-reactive/src/main/java/io/github/jklingsporn/vertx/jooq/shared/reactive/ReactiveQueryResult.java#L24) of `ReactiveQueryResult` is incorrectly assuming there would be at least 1 record returned, which is not the case above.

**Comment by jklingsporn** [comment]
Thank you for your report. I'll look into this.

**Comment by jklingsporn** [comment]
I've uploaded a quickfix into https://github.com/jklingsporn/vertx-jooq/tree/%2398. I need to define though what happens when one calls one of the `get`-methods of the `UnifiedQueryExecutor` when there is no result as the different implementations behave differently for now. 
Should it just return `null` or throw a `NullPointerException`?

**Comment by paninics** [comment]
The quick fix will result in an implicit `NullPointerException` if one blindly calls the `get()` methods of `ReactiveQueryResult`without doing a `hasResults()` check. So if the get methods of `UnifiedQueryExecutor` has something similar (i.e. to determine if results are present or not), perhaps throwing (implicitly or explicitly) `NullPointerException` in the interim is OK. But from an API design point, IMHO it is much clearer to explicitly throw an *unchecked exception* such as `NoSuchElementException` / `NoDataFoundException` as `NullPointerException` wouldn't convey the intention.

**Comment by paninics** [comment]
The above comment was in reference to a data row / result set. On further thought, even if we've a result set, there may not be a value for a particular column / field. In that case, I guess you would have to return a `null` or an `Optional<T>`. With the quick fix you provided, I've run into this issue and get a `NullPointerException` instead.

**Comment by jklingsporn** [comment]
Thanks for your feedback on this. 
If you were running plain jOOQ and issuing a SELECT statement, the result is of type `org.jooq.Result`. Even if the SELECT returns no values, this is never `null` (same as in vertx-jooq for now). If you then call one of the `get` or `getValue`-methods this will throw an `IndexOutOfBoundsException` as the result is backed by an `ArrayList`. 
I'd rather return `null` here and let the caller decide what to do with a `null` result, e.g. `Optional.ofNullable(queryResult.get(MY_FIELD)).orElse(defaultValue)`, simple `null`-check or call `QueryResult#hasResults()`. 
Regarding the overloading of the `get`-methods I prefer to let the user deal with the `null`-values with one of the methods described above (jOOQ will [drop the default value](https://github.com/jOOQ/jOOQ/issues/2878)-methods on their respective `Result` as well).

**Comment by jklingsporn** [comment]
Ah wait. We should maybe distinguish between two scenarios:
1. No result at all
2. There are results, but the result for a specific field is `null`
Otherwise, the user will not know which of the scenarios occurred.

**Comment by paninics** [comment]
That's a good thought. But, as an example, in Postgres database one can either have a value or no value for a given field. The notion of a null value is equivalent to no value. I don't know the behavior of other databases but I would presume they would be similar. If so, we essentially have only two states and hence it may not matter trying to distinguish between absence of a value and a null value. In light of this perhaps you can consider using `Optional<T>`.

1. Absence of a value - Return `Optional.empty()`
2. Presence of a value - Return `Optional.of()`. An empty string would be a valid value, if that is what is stored in the database.

BTW, wouldn't the tri-state (i.e. no result, null result and a valid result) be also dependent upon the database driver behavior?

**Comment by dlkw** [comment]
Hi, from my experience it's quite convenient to have two fetching (or query) methods:
1. named, say, `querySingle`, which returns an `Optional`, either empty or with the single result of the query (possibly throwing if the result consisted of more than one row)
2. named, say `queryList`, which returns a possibly empty List, never `null`.

The callers usually know best when the query is supposed to return a single row or multiple rows.

In the first case, they can conveniently get one single row with easy checking if it is present or not---omitting the overhead of expensively creating an Exception just to check if a row was found or not.

The second case can be used even in the single row case, should the caller not know if more than one row is to be expected (or cowardly not want to make that decision).

I don't know if this approach fits into the general approach taken by jooq or this project, but it's quite a workable approach and, as I said, I made good experiences with it.

**Comment by dlkw** [comment]
I just see that there already is `findOneRow`/`findManyRow` in the ReactiveClassicGenericQueryExecutor for that, along with `query`. So now I am wondering when to use `query` at all?

**Comment by jklingsporn** [comment]
The idea behind the `query`-method is, that you don't have to worry about implementation details of the driver you are using. `findOneRow`/`findManyRow` are specific methods from the reactive `PGClient` that do not exist in the jdbc or async variants of vertx-jooq.

**Comment by wooque** [comment]
@jklingsporn this is still an issue, I'm hitting it with query like this
```
    users.queryExecutor().insertReturning(
      dslContext -> dslContext.insertInto(
        USERS, USERS.NAME, USERS.ELO
      ).values(
        user.name, user.elo
      ).onConflict(
        USERS.NAME, USERS.ELO
      ).doNothing().returning(),
      e -> ((RowImpl) e).getInteger("id")
    );
```
If there is conflict because user already exists query won't return anything, and library will fail with `NoSuchElementException`.
Offending line is ReactiveRXQueryExecutor.java:48
